// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuLL2cMSfo1UoPYSMuCUQRYtuwLkBfc4',
    appId: '1:145845990340:android:ff615f4b470251f780aa91',
    messagingSenderId: '145845990340',
    projectId: 'tech-news-e9c81',
    storageBucket: 'tech-news-e9c81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6BiGfCZvhhc4b679ep2Ww2n8VIjexREk',
    appId: '1:145845990340:ios:e7a6aef2c313df2980aa91',
    messagingSenderId: '145845990340',
    projectId: 'tech-news-e9c81',
    storageBucket: 'tech-news-e9c81.appspot.com',
    androidClientId: '145845990340-ajnr0r5japq0dkedh79gifaal8roas8r.apps.googleusercontent.com',
    iosClientId: '145845990340-a70da9iisfkt3f3dpf2ndr7sjvl4ti6f.apps.googleusercontent.com',
    iosBundleId: 'stephen-essoun.mynews.myNews',
  );
}
